// Component-local i18n dictionary. Page-level metadata (title/subtitle/path)
// lives in Site/src/i18n/strings.ts under the `ajolotes.*` namespace; this
// dict carries everything rendered inside the island.

import type { Locale, SpeciesCode } from './types';

type Dict = Record<string, string>;

export const STRINGS: Record<Locale, Dict> = {
  es: {
    // Cover
    'cover.eyebrow': 'Biomuseo Xolotlcalli · Ajolotes',
    'cover.title': 'Ejemplares vivos en custodia',
    'cover.sub': 'Registro abierto de ejemplares del género Ambystoma bajo cuidado del Biomuseo Xolotlcalli. Cada ficha integra biometría, evaluación física, plan alimentario y registros diarios de consumo.',
    'cover.glance.ejemplares': 'ejemplares',
    'cover.glance.especies': 'especies',
    'cover.glance.bajas': 'Bajas',
    'cover.toWater': 'Calidad de agua',
    // Toolbar
    'toolbar.groupBy.station': 'Por estación',
    'toolbar.groupBy.species': 'Por especie',
    'toolbar.search': 'Buscar',
    // Stations
    'station.AA': 'Estación AA',
    'station.AM': 'Estación AM',
    'station.AD': 'Estación AD',
    'station.Larvario': 'Larvario',
    'station.AM.note': 'Unificada en 2026 — 5 peceras: AM 1 a AM 5',
    'station.count.one': 'ejemplar',
    'station.count.many': 'ejemplares',
    'empty.search': 'Sin coincidencias para «{q}».',
    // Card
    'card.peso': 'peso',
    'card.lt': 'longitud total',
    'card.icc': 'ICC',
    'card.icc.tooltip': 'Índice de condición corporal',
    'card.larva': 'larva',
    'card.noData': 'sin datos',
    // Modal
    'modal.close': 'Cerrar',
    'tab.resumen': 'Resumen',
    'tab.biometria': 'Biometría',
    'tab.medico': 'Historial médico',
    'tab.alimentacion': 'Alimentación',
    'modal.foot.att': 'Atestación EAS pendiente · datos del libro operativo',
    'modal.foot.curador': 'curador',
    // Resumen
    'resumen.identidad': 'Identidad',
    'resumen.alias': 'Alias',
    'resumen.id': 'ID',
    'resumen.pecera': 'Pecera',
    'resumen.especie': 'Especie',
    'resumen.genero': 'Género',
    'resumen.fenotipo': 'Fenotipo',
    'resumen.edad': 'Edad',
    'resumen.estadio': 'Estadio',
    'resumen.marcas': 'Marcas distintivas',
    'resumen.estado': 'Estado clínico',
    'resumen.bcs': 'Condición corporal',
    'resumen.estadoBio': 'Estado biométrico',
    'resumen.respAlim': 'Respuesta alimentaria',
    'resumen.conducta': 'Conductual',
    'resumen.anomalia': 'Anomalía permanente',
    'resumen.bio.title': 'Biometría · última medición',
    'resumen.bio.peso': 'Peso',
    'resumen.bio.lt': 'Longitud total',
    'resumen.bio.lhc': 'LHC',
    'resumen.bio.icc': 'ICC',
    'resumen.bio.cabeza': 'Cabeza/cuerpo',
    'resumen.bio.cola': 'Cola/cuerpo',
    'resumen.bio.asimetria': 'Asimetría branq.',
    'resumen.bio.temp': 'Temp in situ',
    'resumen.consumo.title': 'Último consumo',
    'resumen.consumo.tipo': 'Tipo',
    'resumen.estados.sinDatos': 'sin datos',
    'resumen.estados.sinAlertas': 'sin alertas',
    'genero.h': 'Hembra',
    'genero.m': 'Macho',
    'genero.u': 'Sin sexar',
    // Biometría
    'biometria.peso.title': 'Peso (g)',
    'biometria.lt.title': 'Longitud total / hocico-cloaca (cm)',
    'biometria.lt.serie': 'LT',
    'biometria.lhc.serie': 'LHC',
    'biometria.measurement.one': 'medición',
    'biometria.measurement.many': 'mediciones',
    'biometria.detalladas': 'Mediciones detalladas',
    'biometria.empty': 'Sin registros morfométricos.',
    'biometria.col.fecha': 'Fecha',
    'biometria.col.peso': 'Peso',
    'biometria.col.lt': 'Long. total',
    'biometria.col.lhc': 'LHC',
    'biometria.col.cabeza': 'Cabeza L×A',
    'biometria.col.cuerpo': 'Cuerpo',
    'biometria.col.branquias': 'Branq. izq/der',
    'biometria.col.bcs': 'BCS',
    'biometria.col.autor': 'Autor',
    // Médico
    'medico.empty.title': 'Sin incidencias registradas',
    'medico.empty.sub': 'No hay observaciones clínicas en el historial médico.',
    'medico.label.cabeza': 'Cabeza, ojos y branquias',
    'medico.label.cuerpo': 'Cuerpo',
    'medico.label.extremidades': 'Extremidades',
    'medico.label.cola': 'Cola',
    'medico.label.comportamiento': 'Comportamiento',
    'medico.label.tipo': 'Tipo específico',
    'medico.label.justificacion': 'Justificación',
    'medico.label.notas': 'Notas',
    // Alimentación
    'alim.empty': 'Sin registros de alimentación',
    'alim.section.plan': 'Plan vigente',
    'alim.section.records': 'Registros y consumo',
    'alim.frecuencia': 'Frecuencia semanal',
    'alim.porcion': 'Porción autorizada',
    'alim.dieta': 'Dieta base',
    'alim.planB': 'Plan B',
    'alim.planB.sub': 'rechazo / emergencia',
    'alim.notas': 'Notas clínicas y de preparación',
    'alim.acceptance': 'Tasa de aceptación',
    'alim.acceptance.sub': '{consumo}g de {ofrecido}g ofrecidos',
    'alim.totals': 'Registros totales',
    'alim.totals.sub': 'en {n} día{plural}',
    'alim.daily': 'Consumo promedio diario',
    'alim.daily.sub': 'por día activo',
    'alim.consumo.title': 'Consumo diario (g)',
    'alim.day.one': 'día',
    'alim.day.many': 'días',
    'alim.mezcla.title': 'Mezcla de alimento',
    'alim.mezcla.sub': 'por gramos consumidos',
    'alim.records.title': 'Registros recientes',
    'alim.col.fecha': 'Fecha',
    'alim.col.tipo': 'Tipo',
    'alim.col.ofrecida': 'Ofrecida',
    'alim.col.consumo': 'Consumo',
    'alim.col.sobrante': 'Sobrante',
    'days.Lun': 'Lun', 'days.Mar': 'Mar', 'days.Mie': 'Mié',
    'days.Jue': 'Jue', 'days.Vie': 'Vie', 'days.Sab': 'Sáb', 'days.Dom': 'Dom',
    // Bajas
    'bajas.eyebrow': 'Bajas históricas',
    'bajas.title': 'In memoriam',
    'bajas.sub': 'Registro abierto de los ejemplares que estuvieron bajo nuestro cuidado y ya no están con nosotros. Cada ficha mantiene su última biometría, edad y causa probable de baja, además del estatus de necropsia.',
    'bajas.back': '← Volver a ejemplares vivos',
    'bajas.total': 'bajas registradas',
    'bajas.count.one': 'baja',
    'bajas.count.many': 'bajas',
    'bajas.empty': 'Sin coincidencias.',
    'bajas.peso': 'peso',
    'bajas.longitud': 'longitud',
    'bajas.causa': 'Causa probable',
    'bajas.necro.done': 'Necropsia: ',
    'bajas.necro.pending': 'Necropsia en proceso',
    'bajas.necro.none': 'Sin necropsia',
    // Tweaks
    'tweaks.title': 'Ajustes',
    'tweaks.theme': 'Tema',
    'tweaks.theme.dark': 'Oscuro',
    'tweaks.theme.light': 'Claro',
    'tweaks.locale': 'Idioma',
    'tweaks.groupBy': 'Agrupar',
    'tweaks.groupBy.station': 'Estación',
    'tweaks.groupBy.species': 'Especie',
    'tweaks.larvario': 'Mostrar larvario',
    // Common species names per locale (handoff §8.4 — `commonNames` in
    // src/content/species/*.yaml is Spanish-only, so we keep this here)
    'species.A. andersoni.common': 'Ajolote del Lago Pátzcuaro',
    'species.A. mexicanum.common': 'Ajolote de Xochimilco',
    'species.A. dumerilii.common': 'Ajolote del Lago de Lerma',
  },
  en: {
    'cover.eyebrow': 'Xolotlcalli BioMuseum · Axolotls',
    'cover.title': 'Living specimens in custody',
    'cover.sub': 'Open registry of Ambystoma specimens under the care of the Xolotlcalli BioMuseum. Each record integrates biometry, physical exams, feeding plan, and daily consumption logs.',
    'cover.glance.ejemplares': 'specimens',
    'cover.glance.especies': 'species',
    'cover.glance.bajas': 'In memoriam',
    'cover.toWater': 'Water quality',
    'toolbar.groupBy.station': 'By station',
    'toolbar.groupBy.species': 'By species',
    'toolbar.search': 'Search',
    'station.AA': 'Station AA',
    'station.AM': 'Station AM',
    'station.AD': 'Station AD',
    'station.Larvario': 'Larvae',
    'station.AM.note': 'Unified in 2026 — 5 tanks: AM 1 to AM 5',
    'station.count.one': 'specimen',
    'station.count.many': 'specimens',
    'empty.search': 'No matches for «{q}».',
    'card.peso': 'weight',
    'card.lt': 'total length',
    'card.icc': 'BCI',
    'card.icc.tooltip': 'Body condition index',
    'card.larva': 'larva',
    'card.noData': 'no data',
    'modal.close': 'Close',
    'tab.resumen': 'Summary',
    'tab.biometria': 'Biometry',
    'tab.medico': 'Medical history',
    'tab.alimentacion': 'Feeding',
    'modal.foot.att': 'EAS attestation pending · operativo book data',
    'modal.foot.curador': 'curator',
    'resumen.identidad': 'Identity',
    'resumen.alias': 'Alias',
    'resumen.id': 'ID',
    'resumen.pecera': 'Tank',
    'resumen.especie': 'Species',
    'resumen.genero': 'Sex',
    'resumen.fenotipo': 'Phenotype',
    'resumen.edad': 'Age',
    'resumen.estadio': 'Life stage',
    'resumen.marcas': 'Distinctive marks',
    'resumen.estado': 'Clinical status',
    'resumen.bcs': 'Body condition',
    'resumen.estadoBio': 'Biometric status',
    'resumen.respAlim': 'Feeding response',
    'resumen.conducta': 'Behavior',
    'resumen.anomalia': 'Permanent anomaly',
    'resumen.bio.title': 'Biometry · last measurement',
    'resumen.bio.peso': 'Weight',
    'resumen.bio.lt': 'Total length',
    'resumen.bio.lhc': 'SVL',
    'resumen.bio.icc': 'BCI',
    'resumen.bio.cabeza': 'Head/body',
    'resumen.bio.cola': 'Tail/body',
    'resumen.bio.asimetria': 'Gill asymmetry',
    'resumen.bio.temp': 'Temp in situ',
    'resumen.consumo.title': 'Last meal',
    'resumen.consumo.tipo': 'Type',
    'resumen.estados.sinDatos': 'no data',
    'resumen.estados.sinAlertas': 'no alerts',
    'genero.h': 'Female',
    'genero.m': 'Male',
    'genero.u': 'Unsexed',
    'biometria.peso.title': 'Weight (g)',
    'biometria.lt.title': 'Total length / snout-vent (cm)',
    'biometria.lt.serie': 'TL',
    'biometria.lhc.serie': 'SVL',
    'biometria.measurement.one': 'measurement',
    'biometria.measurement.many': 'measurements',
    'biometria.detalladas': 'Detailed measurements',
    'biometria.empty': 'No morphometric records.',
    'biometria.col.fecha': 'Date',
    'biometria.col.peso': 'Weight',
    'biometria.col.lt': 'Tot. length',
    'biometria.col.lhc': 'SVL',
    'biometria.col.cabeza': 'Head L×W',
    'biometria.col.cuerpo': 'Body',
    'biometria.col.branquias': 'Gills L/R',
    'biometria.col.bcs': 'BCS',
    'biometria.col.autor': 'Author',
    'medico.empty.title': 'No incidents recorded',
    'medico.empty.sub': 'No clinical observations in the medical history.',
    'medico.label.cabeza': 'Head, eyes and gills',
    'medico.label.cuerpo': 'Body',
    'medico.label.extremidades': 'Limbs',
    'medico.label.cola': 'Tail',
    'medico.label.comportamiento': 'Behavior',
    'medico.label.tipo': 'Specific type',
    'medico.label.justificacion': 'Rationale',
    'medico.label.notas': 'Notes',
    'alim.empty': 'No feeding records',
    'alim.section.plan': 'Active plan',
    'alim.section.records': 'Records and consumption',
    'alim.frecuencia': 'Weekly schedule',
    'alim.porcion': 'Authorized portion',
    'alim.dieta': 'Base diet',
    'alim.planB': 'Plan B',
    'alim.planB.sub': 'rejection / emergency',
    'alim.notas': 'Clinical and prep notes',
    'alim.acceptance': 'Acceptance rate',
    'alim.acceptance.sub': '{consumo}g of {ofrecido}g offered',
    'alim.totals': 'Total records',
    'alim.totals.sub': 'over {n} day{plural}',
    'alim.daily': 'Average daily consumption',
    'alim.daily.sub': 'per active day',
    'alim.consumo.title': 'Daily consumption (g)',
    'alim.day.one': 'day',
    'alim.day.many': 'days',
    'alim.mezcla.title': 'Food mix',
    'alim.mezcla.sub': 'by grams consumed',
    'alim.records.title': 'Recent records',
    'alim.col.fecha': 'Date',
    'alim.col.tipo': 'Type',
    'alim.col.ofrecida': 'Offered',
    'alim.col.consumo': 'Eaten',
    'alim.col.sobrante': 'Leftover',
    'days.Lun': 'Mon', 'days.Mar': 'Tue', 'days.Mie': 'Wed',
    'days.Jue': 'Thu', 'days.Vie': 'Fri', 'days.Sab': 'Sat', 'days.Dom': 'Sun',
    'bajas.eyebrow': 'Historic losses',
    'bajas.title': 'In memoriam',
    'bajas.sub': 'Open record of specimens once under our care who are no longer with us. Each entry preserves their last biometry, age, probable cause of loss, and necropsy status.',
    'bajas.back': '← Back to living specimens',
    'bajas.total': 'recorded losses',
    'bajas.count.one': 'loss',
    'bajas.count.many': 'losses',
    'bajas.empty': 'No matches.',
    'bajas.peso': 'weight',
    'bajas.longitud': 'length',
    'bajas.causa': 'Probable cause',
    'bajas.necro.done': 'Necropsy: ',
    'bajas.necro.pending': 'Necropsy in progress',
    'bajas.necro.none': 'No necropsy',
    'tweaks.title': 'Settings',
    'tweaks.theme': 'Theme',
    'tweaks.theme.dark': 'Dark',
    'tweaks.theme.light': 'Light',
    'tweaks.locale': 'Language',
    'tweaks.groupBy': 'Group by',
    'tweaks.groupBy.station': 'Station',
    'tweaks.groupBy.species': 'Species',
    'tweaks.larvario': 'Show larvae',
    'species.A. andersoni.common': 'Pátzcuaro salamander',
    'species.A. mexicanum.common': 'Mexican axolotl',
    'species.A. dumerilii.common': 'Lake Lerma salamander',
  },
  pt: {
    'cover.eyebrow': 'BioMuseu Xolotlcalli · Axolotes',
    'cover.title': 'Exemplares vivos sob custódia',
    'cover.sub': 'Registro aberto de exemplares do gênero Ambystoma sob cuidado do BioMuseu Xolotlcalli. Cada ficha integra biometria, avaliação física, plano alimentar e registros diários de consumo.',
    'cover.glance.ejemplares': 'exemplares',
    'cover.glance.especies': 'espécies',
    'cover.glance.bajas': 'In memoriam',
    'cover.toWater': 'Qualidade da água',
    'toolbar.groupBy.station': 'Por estação',
    'toolbar.groupBy.species': 'Por espécie',
    'toolbar.search': 'Buscar',
    'station.AA': 'Estação AA',
    'station.AM': 'Estação AM',
    'station.AD': 'Estação AD',
    'station.Larvario': 'Larvário',
    'station.AM.note': 'Unificada em 2026 — 5 aquários: AM 1 a AM 5',
    'station.count.one': 'exemplar',
    'station.count.many': 'exemplares',
    'empty.search': 'Sem correspondências para «{q}».',
    'card.peso': 'peso',
    'card.lt': 'comprimento total',
    'card.icc': 'ICC',
    'card.icc.tooltip': 'Índice de condição corporal',
    'card.larva': 'larva',
    'card.noData': 'sem dados',
    'modal.close': 'Fechar',
    'tab.resumen': 'Resumo',
    'tab.biometria': 'Biometria',
    'tab.medico': 'Histórico médico',
    'tab.alimentacion': 'Alimentação',
    'modal.foot.att': 'Atestação EAS pendente · dados do livro operativo',
    'modal.foot.curador': 'curador',
    'resumen.identidad': 'Identidade',
    'resumen.alias': 'Alias',
    'resumen.id': 'ID',
    'resumen.pecera': 'Aquário',
    'resumen.especie': 'Espécie',
    'resumen.genero': 'Sexo',
    'resumen.fenotipo': 'Fenótipo',
    'resumen.edad': 'Idade',
    'resumen.estadio': 'Estádio',
    'resumen.marcas': 'Marcas distintivas',
    'resumen.estado': 'Estado clínico',
    'resumen.bcs': 'Condição corporal',
    'resumen.estadoBio': 'Estado biométrico',
    'resumen.respAlim': 'Resposta alimentar',
    'resumen.conducta': 'Comportamental',
    'resumen.anomalia': 'Anomalia permanente',
    'resumen.bio.title': 'Biometria · última medição',
    'resumen.bio.peso': 'Peso',
    'resumen.bio.lt': 'Comprimento total',
    'resumen.bio.lhc': 'CRC',
    'resumen.bio.icc': 'ICC',
    'resumen.bio.cabeza': 'Cabeça/corpo',
    'resumen.bio.cola': 'Cauda/corpo',
    'resumen.bio.asimetria': 'Assimetria branq.',
    'resumen.bio.temp': 'Temp in situ',
    'resumen.consumo.title': 'Último consumo',
    'resumen.consumo.tipo': 'Tipo',
    'resumen.estados.sinDatos': 'sem dados',
    'resumen.estados.sinAlertas': 'sem alertas',
    'genero.h': 'Fêmea',
    'genero.m': 'Macho',
    'genero.u': 'Não sexado',
    'biometria.peso.title': 'Peso (g)',
    'biometria.lt.title': 'Comprimento total / focinho-cloaca (cm)',
    'biometria.lt.serie': 'CT',
    'biometria.lhc.serie': 'CRC',
    'biometria.measurement.one': 'medição',
    'biometria.measurement.many': 'medições',
    'biometria.detalladas': 'Medições detalhadas',
    'biometria.empty': 'Sem registros morfométricos.',
    'biometria.col.fecha': 'Data',
    'biometria.col.peso': 'Peso',
    'biometria.col.lt': 'Compr. total',
    'biometria.col.lhc': 'CRC',
    'biometria.col.cabeza': 'Cabeça L×A',
    'biometria.col.cuerpo': 'Corpo',
    'biometria.col.branquias': 'Brânq. esq/dir',
    'biometria.col.bcs': 'BCS',
    'biometria.col.autor': 'Autor',
    'medico.empty.title': 'Sem ocorrências registradas',
    'medico.empty.sub': 'Não há observações clínicas no histórico médico.',
    'medico.label.cabeza': 'Cabeça, olhos e brânquias',
    'medico.label.cuerpo': 'Corpo',
    'medico.label.extremidades': 'Extremidades',
    'medico.label.cola': 'Cauda',
    'medico.label.comportamiento': 'Comportamento',
    'medico.label.tipo': 'Tipo específico',
    'medico.label.justificacion': 'Justificativa',
    'medico.label.notas': 'Notas',
    'alim.empty': 'Sem registros de alimentação',
    'alim.section.plan': 'Plano vigente',
    'alim.section.records': 'Registros e consumo',
    'alim.frecuencia': 'Frequência semanal',
    'alim.porcion': 'Porção autorizada',
    'alim.dieta': 'Dieta base',
    'alim.planB': 'Plano B',
    'alim.planB.sub': 'rejeição / emergência',
    'alim.notas': 'Notas clínicas e de preparo',
    'alim.acceptance': 'Taxa de aceitação',
    'alim.acceptance.sub': '{consumo}g de {ofrecido}g oferecidos',
    'alim.totals': 'Registros totais',
    'alim.totals.sub': 'em {n} dia{plural}',
    'alim.daily': 'Consumo médio diário',
    'alim.daily.sub': 'por dia ativo',
    'alim.consumo.title': 'Consumo diário (g)',
    'alim.day.one': 'dia',
    'alim.day.many': 'dias',
    'alim.mezcla.title': 'Mistura de alimento',
    'alim.mezcla.sub': 'por gramas consumidos',
    'alim.records.title': 'Registros recentes',
    'alim.col.fecha': 'Data',
    'alim.col.tipo': 'Tipo',
    'alim.col.ofrecida': 'Oferecida',
    'alim.col.consumo': 'Consumo',
    'alim.col.sobrante': 'Sobra',
    'days.Lun': 'Seg', 'days.Mar': 'Ter', 'days.Mie': 'Qua',
    'days.Jue': 'Qui', 'days.Vie': 'Sex', 'days.Sab': 'Sáb', 'days.Dom': 'Dom',
    'bajas.eyebrow': 'Baixas históricas',
    'bajas.title': 'In memoriam',
    'bajas.sub': 'Registro aberto dos exemplares que estiveram sob nossos cuidados e já não estão conosco. Cada ficha mantém sua última biometria, idade e causa provável da baixa, além do estado da necropsia.',
    'bajas.back': '← Voltar aos exemplares vivos',
    'bajas.total': 'baixas registradas',
    'bajas.count.one': 'baixa',
    'bajas.count.many': 'baixas',
    'bajas.empty': 'Sem correspondências.',
    'bajas.peso': 'peso',
    'bajas.longitud': 'comprimento',
    'bajas.causa': 'Causa provável',
    'bajas.necro.done': 'Necropsia: ',
    'bajas.necro.pending': 'Necropsia em andamento',
    'bajas.necro.none': 'Sem necropsia',
    'tweaks.title': 'Ajustes',
    'tweaks.theme': 'Tema',
    'tweaks.theme.dark': 'Escuro',
    'tweaks.theme.light': 'Claro',
    'tweaks.locale': 'Idioma',
    'tweaks.groupBy': 'Agrupar',
    'tweaks.groupBy.station': 'Estação',
    'tweaks.groupBy.species': 'Espécie',
    'tweaks.larvario': 'Mostrar larvário',
    'species.A. andersoni.common': 'Salamandra de Pátzcuaro',
    'species.A. mexicanum.common': 'Axolote mexicano',
    'species.A. dumerilii.common': 'Salamandra do Lago Lerma',
  },
};

export function s(locale: Locale, key: string, fallback?: string): string {
  return STRINGS[locale]?.[key] ?? STRINGS.es[key] ?? fallback ?? key;
}

export function commonName(locale: Locale, species: SpeciesCode | string | null | undefined): string {
  if (!species) return '';
  return STRINGS[locale]?.[`species.${species}.common`] ?? '';
}

export function genderTitle(locale: Locale, g: string | null | undefined): string {
  if (!g) return s(locale, 'genero.u');
  const x = String(g).toLowerCase();
  if (x.startsWith('hembra')) return s(locale, 'genero.h');
  if (x.startsWith('macho')) return s(locale, 'genero.m');
  return s(locale, 'genero.u');
}

// Shared date formatter — reuses the waterQuality month dictionary.
import { monthLabel } from '../waterQuality/strings';

export function formatDateLong(locale: Locale, iso: string | null | undefined): string {
  if (!iso) return '—';
  const [y, m, d] = iso.split('-').map(Number);
  if (!y || !m || !d) return iso;
  const month = monthLabel(locale, m - 1);
  if (locale === 'en') return `${month} ${d}, ${y}`;
  return `${d} de ${month} ${y}`;
}
