// Component-local i18n dictionary. Page-level metadata (title/subtitle/path)
// lives in Site/src/i18n/strings.ts under the `ajolotes.*` namespace; this
// dict carries everything rendered inside the island.

import type { Locale, SpeciesCode } from './types';

type Dict = Record<string, string>;

export const STRINGS: Record<Locale, Dict> = {
  es: {
    // Cover
    'cover.eyebrow': 'Biomuseo Xolotlcalli · Ajolotes',
    'cover.title': 'Ajolotes del Biomuseo',
    'cover.sub': 'Ejemplares vivos en custodia',
    'cover.glance.ejemplares': 'ejemplares',
    'cover.glance.especies': 'especies',
    'cover.glance.bajas': 'Bajas',
    'cover.toWater': 'Calidad de agua',
    // Toolbar
    'toolbar.groupBy.station': 'Por estación',
    'toolbar.groupBy.species': 'Por especie',
    'toolbar.search': 'Buscar',
    // Stations
    'station.AA': 'Estación AA',
    'station.AM': 'Estación AM',
    'station.AD': 'Estación AD',
    'station.Larvario': 'Larvario',
    'station.count.one': 'ejemplar',
    'station.count.many': 'ejemplares',
    'pecera.station': 'Estación',
    'pecera.aquarium': 'Acuario',
    'cover.glance.total': 'ejemplares',
    'empty.search': 'Sin coincidencias para «{q}».',
    'view.gallery': 'Galería',
    'view.list': 'Lista',
    'stage.larva': 'larva',
    'stage.juvenil': 'juvenil',
    'stage.subadulto': 'subadulto',
    'stage.adulto': 'adulto',
    'stage.unknown': 'sin etapa',
    // Card
    'card.peso': 'peso',
    'card.lt': 'longitud total',
    'card.icc': 'ICC',
    'card.icc.tooltip': 'Índice de condición corporal · masa relativa al tamaño.',
    'card.lhc.tooltip': 'Longitud hocico-cloaca · medida desde la punta del hocico hasta la cloaca.',
    'card.lt.tooltip': 'Longitud total · de la punta del hocico al final de la cola.',
    'card.bcs.tooltip': 'Body Condition Score · escala visual 1–5 de condición corporal.',
    'card.larva': 'larva',
    'card.noData': 'sin datos',
    'card.semarnat': 'SEMARNAT ID',
    'card.semarnat.tooltip': 'Identificador del registro SEMARNAT',
    // Modal
    'modal.close': 'Cerrar',
    'xovi.clip': 'Ver en Xovi',
    'modal.ribbon.cuarentena': 'En cuarentena',
    'tab.resumen': 'Resumen',
    'tab.biometria': 'Biometría',
    'tab.eventos': 'Eventos',
    'tab.alimentacion': 'Alimentación',
    'modal.foot.att': 'Atestación EAS pendiente · datos del libro operativo',
    'modal.foot.curador': 'curador',
    // Resumen
    'resumen.identidad': 'Identidad',
    'resumen.alias': 'Alias',
    'resumen.id': 'ID',
    'resumen.pecera': 'Pecera',
    'resumen.especie': 'Especie',
    'resumen.genero': 'Género',
    'resumen.fenotipo': 'Fenotipo',
    'resumen.edad': 'Edad',
    'resumen.estadio': 'Estadio',
    'resumen.marcas': 'Marcas distintivas',
    'resumen.estado': 'Estado clínico',
    'resumen.bcs': 'Condición corporal',
    'resumen.estadoBio': 'Estado biométrico',
    'resumen.respAlim': 'Respuesta alimentaria',
    'resumen.conducta': 'Conductual',
    'resumen.anomalia': 'Anomalía permanente',
    'resumen.leerMas': 'Leer más',
    'resumen.leerMenos': 'Leer menos',
    'resumen.bio.title': 'Biometría · última medición',
    'resumen.bio.peso': 'Peso',
    'resumen.bio.lt': 'Longitud total',
    'resumen.bio.lhc': 'LHC',
    'resumen.bio.icc': 'ICC',
    'resumen.bio.cabeza': 'Cabeza/cuerpo',
    'resumen.bio.cola': 'Cola/cuerpo',
    'resumen.bio.asimetria': 'Asimetría branq.',
    'resumen.bio.temp': 'Temp in situ',
    'resumen.bio.date': 'medición:',
    'resumen.consumo.title': 'Último consumo',
    'resumen.consumo.tipo': 'Tipo',
    'resumen.estados.sinDatos': 'sin datos',
    'resumen.estados.sinAlertas': 'sin alertas',
    'resumen.water.title': 'Calidad del agua del acuario',
    'resumen.water.latest': 'medición más reciente:',
    'resumen.water.inSitu': 'Temp in situ',
    'resumen.water.inSitu.tooltip': 'Temperatura registrada durante el examen biométrico del ejemplar.',
    'resumen.water.stale': 'al',
    'resumen.water.staleTooltip': 'Sin lectura en la medición más reciente. Valor de respaldo del',
    'resumen.water.openStation': 'Abrir esta estación en Calidad de agua',
    'water.temp': 'Temperatura',
    'water.temp.tooltip': 'Temperatura del agua (°C).',
    'water.ph': 'pH',
    'water.ph.tooltip': 'Potencial de hidrógeno · acidez/alcalinidad del agua.',
    'water.no2': 'NO₂',
    'water.no2.tooltip': 'Nitritos (mg/L) · subproducto tóxico del ciclo del nitrógeno.',
    'water.no3': 'NO₃',
    'water.no3.tooltip': 'Nitratos (mg/L) · producto final del ciclo del nitrógeno.',
    'water.gh': 'GH',
    'water.gh.tooltip': 'Dureza general (mg/L) · concentración de Ca²⁺ y Mg²⁺.',
    'water.kh': 'KH',
    'water.kh.tooltip': 'Dureza de carbonatos (mg/L) · capacidad amortiguadora del agua.',
    'water.nh3': 'NH₃',
    'water.nh3.tooltip': 'Amoniaco (mg/L) · forma tóxica del nitrógeno.',
    'water.po4': 'PO₄',
    'water.po4.tooltip': 'Fosfatos (mg/L).',
    'water.cond': 'Conductividad',
    'water.cond.tooltip': 'Conductividad eléctrica del agua (µS/cm).',
    'water.tds': 'TDS',
    'water.tds.tooltip': 'Sólidos disueltos totales (mg/L).',
    'genero.h': 'Hembra',
    'genero.m': 'Macho',
    'genero.u': 'Sin sexar',
    // Biometría
    'biometria.peso.title': 'Peso (g)',
    'biometria.lt.title': 'Longitud total / hocico-cloaca (cm)',
    'biometria.lt.serie': 'LT',
    'biometria.lhc.serie': 'LHC',
    'biometria.measurement.one': 'medición',
    'biometria.measurement.many': 'mediciones',
    'biometria.detalladas': 'Mediciones detalladas',
    'biometria.empty': 'Sin registros morfométricos.',
    'biometria.col.fecha': 'Fecha',
    'biometria.col.peso': 'Peso',
    'biometria.col.lt': 'Long. total',
    'biometria.col.lhc': 'LHC',
    'biometria.col.cabeza': 'Cabeza L×A',
    'biometria.col.cuerpo': 'Cuerpo',
    'biometria.col.branquias': 'Branq. izq/der',
    'biometria.col.bcs': 'BCS',
    'biometria.col.autor': 'Autor',
    // Eventos (multi-source timeline)
    'eventos.empty.title': 'Sin eventos registrados',
    'eventos.empty.sub': 'Sin actividad clínica, terapéutica u operativa en el registro.',
    'eventos.source.historial': 'Médico',
    'eventos.source.terapeutica': 'Terapéutica',
    'eventos.source.bitacora': 'Bitácora',
    'eventos.source.baja': 'Baja',
    'eventos.filter.all': 'Todos',
    'eventos.filter.showAll': 'Mostrar todos',
    'eventos.state.ok': 'Resueltos',
    'eventos.state.warn': 'Activos',
    'eventos.state.alarm': 'Críticos',
    'eventos.label.tratamiento': 'Tratamiento',
    'eventos.label.dosis': 'Dosis · vía',
    'eventos.label.estado': 'Estado',
    'eventos.label.ubicacion': 'Ubicación',
    'eventos.label.incidencia': 'Incidencia',
    'eventos.label.accion': 'Acción tomada',
    'eventos.label.dia': 'Día de tratamiento',
    'eventos.label.diagnostico': 'Diagnóstico',
    'medico.label.cabeza': 'Cabeza, ojos y branquias',
    'medico.label.cuerpo': 'Cuerpo',
    'medico.label.extremidades': 'Extremidades',
    'medico.label.cola': 'Cola',
    'medico.label.comportamiento': 'Comportamiento',
    'medico.label.tipo': 'Tipo específico',
    'medico.label.justificacion': 'Justificación',
    'medico.label.notas': 'Notas',
    // Alimentación
    'alim.empty': 'Sin registros de alimentación',
    'alim.section.plan': 'Plan vigente',
    'alim.section.records': 'Registros y consumo',
    'alim.frecuencia': 'Frecuencia semanal',
    'alim.porcion': 'Porción autorizada',
    'alim.dieta': 'Dieta base',
    'alim.planB': 'Plan B',
    'alim.planB.sub': 'rechazo / emergencia',
    'alim.notas': 'Notas clínicas y de preparación',
    'alim.acceptance': 'Tasa de aceptación',
    'alim.acceptance.sub': '{consumo}g de {ofrecido}g ofrecidos',
    'alim.totals': 'Registros totales',
    'alim.totals.sub': 'en {n} día{plural}',
    'alim.daily': 'Consumo promedio diario',
    'alim.daily.sub': 'por día activo',
    'alim.consumo.title': 'Consumo diario (g)',
    'alim.day.one': 'día',
    'alim.day.many': 'días',
    'alim.mezcla.title': 'Mezcla de alimento',
    'alim.mezcla.sub': 'por gramos consumidos',
    'alim.records.title': 'Registros recientes',
    'alim.col.fecha': 'Fecha',
    'alim.col.tipo': 'Tipo',
    'alim.col.ofrecida': 'Ofrecida',
    'alim.col.consumo': 'Consumo',
    'alim.col.sobrante': 'Sobrante',
    'alim.lastMeal': 'Último consumo',
    'alim.lastMeal.empty': 'Sin registros',
    'days.Lun': 'Lun', 'days.Mar': 'Mar', 'days.Mie': 'Mié',
    'days.Jue': 'Jue', 'days.Vie': 'Vie', 'days.Sab': 'Sáb', 'days.Dom': 'Dom',
    // Bajas
    'bajas.eyebrow': 'Bajas históricas',
    'bajas.title': 'In memoriam',
    'bajas.sub': 'Registro abierto de los ejemplares que estuvieron bajo nuestro cuidado y ya no están con nosotros. Cada ficha mantiene su última biometría, edad y causa probable de baja, además del estatus de necropsia.',
    'bajas.back': '← Volver a ejemplares vivos',
    'bajas.total': 'bajas registradas',
    'bajas.count.one': 'baja',
    'bajas.count.many': 'bajas',
    'bajas.empty': 'Sin coincidencias.',
    'bajas.peso': 'peso',
    'bajas.longitud': 'longitud',
    'bajas.causa': 'Causa probable',
    'bajas.necro.done': 'Necropsia: ',
    'bajas.necro.pending': 'Necropsia en proceso',
    'bajas.necro.none': 'Sin necropsia',
    'bajas.open': 'Ver ficha memorial',
    'bajas.hint': 'Toca para ver su historia',
    'bajas.memorial.badge': 'En memoria',
    'bajas.memorial.edad': 'Edad',
    'bajas.memorial.firstRecord': 'Primer registro',
    'bajas.memorial.lastRecord': 'Último registro',
    'bajas.memorial.weightTrend': 'Tendencia de peso',
    'modal.memorial.badge': 'En memoria',
    // Tweaks
    'tweaks.title': 'Ajustes',
    'tweaks.theme': 'Tema',
    'tweaks.theme.dark': 'Oscuro',
    'tweaks.theme.light': 'Claro',
    'tweaks.locale': 'Idioma',
    'tweaks.groupBy': 'Agrupar',
    'tweaks.groupBy.station': 'Estación',
    'tweaks.groupBy.species': 'Especie',
    'tweaks.larvario': 'Mostrar larvario',
    // Common species names per locale (handoff §8.4 — `commonNames` in
    // src/content/species/*.yaml is Spanish-only, so we keep this here)
    'species.A. andersoni.common': 'Ajolote del Lago de Zacapu',
    'species.A. mexicanum.common': 'Ajolote de Xochimilco',
    'species.A. dumerilii.common': 'Ajolote del Lago de Pátzcuaro',
  },
  en: {
    'cover.eyebrow': 'Xolotlcalli BioMuseum · Axolotls',
    'cover.title': 'Axolotls of the Biomuseo',
    'cover.sub': 'Living specimens in custody',
    'cover.glance.ejemplares': 'specimens',
    'cover.glance.especies': 'species',
    'cover.glance.bajas': 'In memoriam',
    'cover.toWater': 'Water quality',
    'toolbar.groupBy.station': 'By station',
    'toolbar.groupBy.species': 'By species',
    'toolbar.search': 'Search',
    'station.AA': 'Station AA',
    'station.AM': 'Station AM',
    'station.AD': 'Station AD',
    'station.Larvario': 'Larvae',
    'station.count.one': 'specimen',
    'station.count.many': 'specimens',
    'pecera.station': 'Station',
    'pecera.aquarium': 'Aquarium',
    'cover.glance.total': 'specimens',
    'empty.search': 'No matches for «{q}».',
    'view.gallery': 'Gallery',
    'view.list': 'List',
    'stage.larva': 'larva',
    'stage.juvenil': 'juvenile',
    'stage.subadulto': 'subadult',
    'stage.adulto': 'adult',
    'stage.unknown': 'no stage',
    'card.peso': 'weight',
    'card.lt': 'total length',
    'card.icc': 'BCI',
    'card.icc.tooltip': 'Body condition index · weight relative to length.',
    'card.lhc.tooltip': 'Snout-vent length · from snout tip to vent.',
    'card.lt.tooltip': 'Total length · snout tip to tail tip.',
    'card.bcs.tooltip': 'Body Condition Score · 1–5 visual scoring scale.',
    'card.larva': 'larva',
    'card.noData': 'no data',
    'card.semarnat': 'SEMARNAT ID',
    'card.semarnat.tooltip': 'SEMARNAT registry identifier',
    'modal.close': 'Close',
    'xovi.clip': 'View on Xovi',
    'modal.ribbon.cuarentena': 'In quarantine',
    'tab.resumen': 'Summary',
    'tab.biometria': 'Biometry',
    'tab.eventos': 'Events',
    'tab.alimentacion': 'Feeding',
    'modal.foot.att': 'EAS attestation pending · operativo book data',
    'modal.foot.curador': 'curator',
    'resumen.identidad': 'Identity',
    'resumen.alias': 'Alias',
    'resumen.id': 'ID',
    'resumen.pecera': 'Tank',
    'resumen.especie': 'Species',
    'resumen.genero': 'Sex',
    'resumen.fenotipo': 'Phenotype',
    'resumen.edad': 'Age',
    'resumen.estadio': 'Life stage',
    'resumen.marcas': 'Distinctive marks',
    'resumen.estado': 'Clinical status',
    'resumen.bcs': 'Body condition',
    'resumen.estadoBio': 'Biometric status',
    'resumen.respAlim': 'Feeding response',
    'resumen.conducta': 'Behavior',
    'resumen.anomalia': 'Permanent anomaly',
    'resumen.leerMas': 'Read more',
    'resumen.leerMenos': 'Read less',
    'resumen.bio.title': 'Biometry · last measurement',
    'resumen.bio.peso': 'Weight',
    'resumen.bio.lt': 'Total length',
    'resumen.bio.lhc': 'SVL',
    'resumen.bio.icc': 'BCI',
    'resumen.bio.cabeza': 'Head/body',
    'resumen.bio.cola': 'Tail/body',
    'resumen.bio.asimetria': 'Gill asymmetry',
    'resumen.bio.temp': 'Temp in situ',
    'resumen.bio.date': 'measured:',
    'resumen.consumo.title': 'Last meal',
    'resumen.consumo.tipo': 'Type',
    'resumen.estados.sinDatos': 'no data',
    'resumen.estados.sinAlertas': 'no alerts',
    'resumen.water.title': 'Tank water quality',
    'resumen.water.latest': 'latest measurement:',
    'resumen.water.inSitu': 'Temp in situ',
    'resumen.water.inSitu.tooltip': 'Temperature recorded during the specimen\'s biometric exam.',
    'resumen.water.stale': 'as of',
    'resumen.water.staleTooltip': 'Not in the latest reading. Fallback value from',
    'resumen.water.openStation': 'Open this station in Water quality',
    'water.temp': 'Temperature',
    'water.temp.tooltip': 'Water temperature (°C).',
    'water.ph': 'pH',
    'water.ph.tooltip': 'Potential of hydrogen · water acidity / alkalinity.',
    'water.no2': 'NO₂',
    'water.no2.tooltip': 'Nitrite (mg/L) · toxic byproduct of the nitrogen cycle.',
    'water.no3': 'NO₃',
    'water.no3.tooltip': 'Nitrate (mg/L) · end product of the nitrogen cycle.',
    'water.gh': 'GH',
    'water.gh.tooltip': 'General hardness (mg/L) · Ca²⁺ and Mg²⁺ concentration.',
    'water.kh': 'KH',
    'water.kh.tooltip': 'Carbonate hardness (mg/L) · pH buffering capacity.',
    'water.nh3': 'NH₃',
    'water.nh3.tooltip': 'Ammonia (mg/L) · toxic form of nitrogen.',
    'water.po4': 'PO₄',
    'water.po4.tooltip': 'Phosphate (mg/L).',
    'water.cond': 'Conductivity',
    'water.cond.tooltip': 'Electrical conductivity (µS/cm).',
    'water.tds': 'TDS',
    'water.tds.tooltip': 'Total dissolved solids (mg/L).',
    'genero.h': 'Female',
    'genero.m': 'Male',
    'genero.u': 'Unsexed',
    'biometria.peso.title': 'Weight (g)',
    'biometria.lt.title': 'Total length / snout-vent (cm)',
    'biometria.lt.serie': 'TL',
    'biometria.lhc.serie': 'SVL',
    'biometria.measurement.one': 'measurement',
    'biometria.measurement.many': 'measurements',
    'biometria.detalladas': 'Detailed measurements',
    'biometria.empty': 'No morphometric records.',
    'biometria.col.fecha': 'Date',
    'biometria.col.peso': 'Weight',
    'biometria.col.lt': 'Tot. length',
    'biometria.col.lhc': 'SVL',
    'biometria.col.cabeza': 'Head L×W',
    'biometria.col.cuerpo': 'Body',
    'biometria.col.branquias': 'Gills L/R',
    'biometria.col.bcs': 'BCS',
    'biometria.col.autor': 'Author',
    'eventos.empty.title': 'No events recorded',
    'eventos.empty.sub': 'No clinical, therapeutic, or operational activity in the record.',
    'eventos.source.historial': 'Clinical',
    'eventos.source.terapeutica': 'Treatment',
    'eventos.source.bitacora': 'Log',
    'eventos.source.baja': 'Loss',
    'eventos.filter.all': 'All',
    'eventos.filter.showAll': 'Show all',
    'eventos.state.ok': 'Resolved',
    'eventos.state.warn': 'Active',
    'eventos.state.alarm': 'Critical',
    'eventos.label.tratamiento': 'Treatment',
    'eventos.label.dosis': 'Dose · route',
    'eventos.label.estado': 'Status',
    'eventos.label.ubicacion': 'Location',
    'eventos.label.incidencia': 'Incident',
    'eventos.label.accion': 'Action taken',
    'eventos.label.dia': 'Treatment day',
    'eventos.label.diagnostico': 'Diagnosis',
    'medico.label.cabeza': 'Head, eyes and gills',
    'medico.label.cuerpo': 'Body',
    'medico.label.extremidades': 'Limbs',
    'medico.label.cola': 'Tail',
    'medico.label.comportamiento': 'Behavior',
    'medico.label.tipo': 'Specific type',
    'medico.label.justificacion': 'Rationale',
    'medico.label.notas': 'Notes',
    'alim.empty': 'No feeding records',
    'alim.section.plan': 'Active plan',
    'alim.section.records': 'Records and consumption',
    'alim.frecuencia': 'Weekly schedule',
    'alim.porcion': 'Authorized portion',
    'alim.dieta': 'Base diet',
    'alim.planB': 'Plan B',
    'alim.planB.sub': 'rejection / emergency',
    'alim.notas': 'Clinical and prep notes',
    'alim.acceptance': 'Acceptance rate',
    'alim.acceptance.sub': '{consumo}g of {ofrecido}g offered',
    'alim.totals': 'Total records',
    'alim.totals.sub': 'over {n} day{plural}',
    'alim.daily': 'Average daily consumption',
    'alim.daily.sub': 'per active day',
    'alim.consumo.title': 'Daily consumption (g)',
    'alim.day.one': 'day',
    'alim.day.many': 'days',
    'alim.mezcla.title': 'Food mix',
    'alim.mezcla.sub': 'by grams consumed',
    'alim.records.title': 'Recent records',
    'alim.col.fecha': 'Date',
    'alim.col.tipo': 'Type',
    'alim.col.ofrecida': 'Offered',
    'alim.col.consumo': 'Eaten',
    'alim.col.sobrante': 'Leftover',
    'alim.lastMeal': 'Last meal',
    'alim.lastMeal.empty': 'No records',
    'days.Lun': 'Mon', 'days.Mar': 'Tue', 'days.Mie': 'Wed',
    'days.Jue': 'Thu', 'days.Vie': 'Fri', 'days.Sab': 'Sat', 'days.Dom': 'Sun',
    'bajas.eyebrow': 'Historic losses',
    'bajas.title': 'In memoriam',
    'bajas.sub': 'Open record of specimens once under our care who are no longer with us. Each entry preserves their last biometry, age, probable cause of loss, and necropsy status.',
    'bajas.back': '← Back to living specimens',
    'bajas.total': 'recorded losses',
    'bajas.count.one': 'loss',
    'bajas.count.many': 'losses',
    'bajas.empty': 'No matches.',
    'bajas.peso': 'weight',
    'bajas.longitud': 'length',
    'bajas.causa': 'Probable cause',
    'bajas.necro.done': 'Necropsy: ',
    'bajas.necro.pending': 'Necropsy in progress',
    'bajas.necro.none': 'No necropsy',
    'bajas.open': 'Open memorial profile',
    'bajas.hint': 'Tap to see their story',
    'bajas.memorial.badge': 'In memoriam',
    'bajas.memorial.edad': 'Age',
    'bajas.memorial.firstRecord': 'First record',
    'bajas.memorial.lastRecord': 'Last record',
    'bajas.memorial.weightTrend': 'Weight trend',
    'modal.memorial.badge': 'In memoriam',
    'tweaks.title': 'Settings',
    'tweaks.theme': 'Theme',
    'tweaks.theme.dark': 'Dark',
    'tweaks.theme.light': 'Light',
    'tweaks.locale': 'Language',
    'tweaks.groupBy': 'Group by',
    'tweaks.groupBy.station': 'Station',
    'tweaks.groupBy.species': 'Species',
    'tweaks.larvario': 'Show larvae',
    'species.A. andersoni.common': 'Lake Zacapu salamander',
    'species.A. mexicanum.common': 'Mexican axolotl',
    'species.A. dumerilii.common': 'Lake Pátzcuaro salamander',
  },
  pt: {
    'cover.eyebrow': 'BioMuseu Xolotlcalli · Axolotes',
    'cover.title': 'Axolotes do Biomuseu',
    'cover.sub': 'Exemplares vivos sob custódia',
    'cover.glance.ejemplares': 'exemplares',
    'cover.glance.especies': 'espécies',
    'cover.glance.bajas': 'In memoriam',
    'cover.toWater': 'Qualidade da água',
    'toolbar.groupBy.station': 'Por estação',
    'toolbar.groupBy.species': 'Por espécie',
    'toolbar.search': 'Buscar',
    'station.AA': 'Estação AA',
    'station.AM': 'Estação AM',
    'station.AD': 'Estação AD',
    'station.Larvario': 'Larvário',
    'station.count.one': 'exemplar',
    'station.count.many': 'exemplares',
    'pecera.station': 'Estação',
    'pecera.aquarium': 'Aquário',
    'cover.glance.total': 'exemplares',
    'empty.search': 'Sem correspondências para «{q}».',
    'view.gallery': 'Galeria',
    'view.list': 'Lista',
    'stage.larva': 'larva',
    'stage.juvenil': 'juvenil',
    'stage.subadulto': 'subadulto',
    'stage.adulto': 'adulto',
    'stage.unknown': 'sem estádio',
    'card.peso': 'peso',
    'card.lt': 'comprimento total',
    'card.icc': 'ICC',
    'card.icc.tooltip': 'Índice de condição corporal · massa relativa ao tamanho.',
    'card.lhc.tooltip': 'Comprimento focinho-cloaca · da ponta do focinho à cloaca.',
    'card.lt.tooltip': 'Comprimento total · da ponta do focinho à ponta da cauda.',
    'card.bcs.tooltip': 'Body Condition Score · escala visual 1–5.',
    'card.larva': 'larva',
    'card.noData': 'sem dados',
    'card.semarnat': 'SEMARNAT ID',
    'card.semarnat.tooltip': 'Identificador do registro SEMARNAT',
    'modal.close': 'Fechar',
    'xovi.clip': 'Ver no Xovi',
    'modal.ribbon.cuarentena': 'Em quarentena',
    'tab.resumen': 'Resumo',
    'tab.biometria': 'Biometria',
    'tab.eventos': 'Eventos',
    'tab.alimentacion': 'Alimentação',
    'modal.foot.att': 'Atestação EAS pendente · dados do livro operativo',
    'modal.foot.curador': 'curador',
    'resumen.identidad': 'Identidade',
    'resumen.alias': 'Alias',
    'resumen.id': 'ID',
    'resumen.pecera': 'Aquário',
    'resumen.especie': 'Espécie',
    'resumen.genero': 'Sexo',
    'resumen.fenotipo': 'Fenótipo',
    'resumen.edad': 'Idade',
    'resumen.estadio': 'Estádio',
    'resumen.marcas': 'Marcas distintivas',
    'resumen.estado': 'Estado clínico',
    'resumen.bcs': 'Condição corporal',
    'resumen.estadoBio': 'Estado biométrico',
    'resumen.respAlim': 'Resposta alimentar',
    'resumen.conducta': 'Comportamental',
    'resumen.anomalia': 'Anomalia permanente',
    'resumen.leerMas': 'Ler mais',
    'resumen.leerMenos': 'Ler menos',
    'resumen.bio.title': 'Biometria · última medição',
    'resumen.bio.peso': 'Peso',
    'resumen.bio.lt': 'Comprimento total',
    'resumen.bio.lhc': 'CRC',
    'resumen.bio.icc': 'ICC',
    'resumen.bio.cabeza': 'Cabeça/corpo',
    'resumen.bio.cola': 'Cauda/corpo',
    'resumen.bio.asimetria': 'Assimetria branq.',
    'resumen.bio.temp': 'Temp in situ',
    'resumen.bio.date': 'medição:',
    'resumen.consumo.title': 'Último consumo',
    'resumen.consumo.tipo': 'Tipo',
    'resumen.estados.sinDatos': 'sem dados',
    'resumen.estados.sinAlertas': 'sem alertas',
    'resumen.water.title': 'Qualidade da água do aquário',
    'resumen.water.latest': 'medição mais recente:',
    'resumen.water.inSitu': 'Temp in situ',
    'resumen.water.inSitu.tooltip': 'Temperatura registrada no exame biométrico do exemplar.',
    'resumen.water.stale': 'em',
    'resumen.water.staleTooltip': 'Sem leitura na medição mais recente. Valor anterior de',
    'resumen.water.openStation': 'Abrir esta estação em Qualidade da água',
    'water.temp': 'Temperatura',
    'water.temp.tooltip': 'Temperatura da água (°C).',
    'water.ph': 'pH',
    'water.ph.tooltip': 'Potencial hidrogeniônico · acidez/alcalinidade da água.',
    'water.no2': 'NO₂',
    'water.no2.tooltip': 'Nitritos (mg/L) · subproduto tóxico do ciclo do nitrogênio.',
    'water.no3': 'NO₃',
    'water.no3.tooltip': 'Nitratos (mg/L) · produto final do ciclo do nitrogênio.',
    'water.gh': 'GH',
    'water.gh.tooltip': 'Dureza geral (mg/L) · concentração de Ca²⁺ e Mg²⁺.',
    'water.kh': 'KH',
    'water.kh.tooltip': 'Dureza de carbonatos (mg/L) · capacidade tampão da água.',
    'water.nh3': 'NH₃',
    'water.nh3.tooltip': 'Amônia (mg/L) · forma tóxica do nitrogênio.',
    'water.po4': 'PO₄',
    'water.po4.tooltip': 'Fosfatos (mg/L).',
    'water.cond': 'Condutividade',
    'water.cond.tooltip': 'Condutividade elétrica (µS/cm).',
    'water.tds': 'TDS',
    'water.tds.tooltip': 'Sólidos dissolvidos totais (mg/L).',
    'genero.h': 'Fêmea',
    'genero.m': 'Macho',
    'genero.u': 'Não sexado',
    'biometria.peso.title': 'Peso (g)',
    'biometria.lt.title': 'Comprimento total / focinho-cloaca (cm)',
    'biometria.lt.serie': 'CT',
    'biometria.lhc.serie': 'CRC',
    'biometria.measurement.one': 'medição',
    'biometria.measurement.many': 'medições',
    'biometria.detalladas': 'Medições detalhadas',
    'biometria.empty': 'Sem registros morfométricos.',
    'biometria.col.fecha': 'Data',
    'biometria.col.peso': 'Peso',
    'biometria.col.lt': 'Compr. total',
    'biometria.col.lhc': 'CRC',
    'biometria.col.cabeza': 'Cabeça L×A',
    'biometria.col.cuerpo': 'Corpo',
    'biometria.col.branquias': 'Brânq. esq/dir',
    'biometria.col.bcs': 'BCS',
    'biometria.col.autor': 'Autor',
    'eventos.empty.title': 'Sem eventos registrados',
    'eventos.empty.sub': 'Sem atividade clínica, terapêutica ou operacional no registro.',
    'eventos.source.historial': 'Médico',
    'eventos.source.terapeutica': 'Terapêutica',
    'eventos.source.bitacora': 'Bitácora',
    'eventos.source.baja': 'Baixa',
    'eventos.filter.all': 'Todos',
    'eventos.filter.showAll': 'Mostrar todos',
    'eventos.state.ok': 'Resolvidos',
    'eventos.state.warn': 'Ativos',
    'eventos.state.alarm': 'Críticos',
    'eventos.label.tratamiento': 'Tratamento',
    'eventos.label.dosis': 'Dose · via',
    'eventos.label.estado': 'Estado',
    'eventos.label.ubicacion': 'Local',
    'eventos.label.incidencia': 'Incidência',
    'eventos.label.accion': 'Ação tomada',
    'eventos.label.dia': 'Dia de tratamento',
    'eventos.label.diagnostico': 'Diagnóstico',
    'medico.label.cabeza': 'Cabeça, olhos e brânquias',
    'medico.label.cuerpo': 'Corpo',
    'medico.label.extremidades': 'Extremidades',
    'medico.label.cola': 'Cauda',
    'medico.label.comportamiento': 'Comportamento',
    'medico.label.tipo': 'Tipo específico',
    'medico.label.justificacion': 'Justificativa',
    'medico.label.notas': 'Notas',
    'alim.empty': 'Sem registros de alimentação',
    'alim.section.plan': 'Plano vigente',
    'alim.section.records': 'Registros e consumo',
    'alim.frecuencia': 'Frequência semanal',
    'alim.porcion': 'Porção autorizada',
    'alim.dieta': 'Dieta base',
    'alim.planB': 'Plano B',
    'alim.planB.sub': 'rejeição / emergência',
    'alim.notas': 'Notas clínicas e de preparo',
    'alim.acceptance': 'Taxa de aceitação',
    'alim.acceptance.sub': '{consumo}g de {ofrecido}g oferecidos',
    'alim.totals': 'Registros totais',
    'alim.totals.sub': 'em {n} dia{plural}',
    'alim.daily': 'Consumo médio diário',
    'alim.daily.sub': 'por dia ativo',
    'alim.consumo.title': 'Consumo diário (g)',
    'alim.day.one': 'dia',
    'alim.day.many': 'dias',
    'alim.mezcla.title': 'Mistura de alimento',
    'alim.mezcla.sub': 'por gramas consumidos',
    'alim.records.title': 'Registros recentes',
    'alim.col.fecha': 'Data',
    'alim.col.tipo': 'Tipo',
    'alim.col.ofrecida': 'Oferecida',
    'alim.col.consumo': 'Consumo',
    'alim.col.sobrante': 'Sobra',
    'alim.lastMeal': 'Último consumo',
    'alim.lastMeal.empty': 'Sem registros',
    'days.Lun': 'Seg', 'days.Mar': 'Ter', 'days.Mie': 'Qua',
    'days.Jue': 'Qui', 'days.Vie': 'Sex', 'days.Sab': 'Sáb', 'days.Dom': 'Dom',
    'bajas.eyebrow': 'Baixas históricas',
    'bajas.title': 'In memoriam',
    'bajas.sub': 'Registro aberto dos exemplares que estiveram sob nossos cuidados e já não estão conosco. Cada ficha mantém sua última biometria, idade e causa provável da baixa, além do estado da necropsia.',
    'bajas.back': '← Voltar aos exemplares vivos',
    'bajas.total': 'baixas registradas',
    'bajas.count.one': 'baixa',
    'bajas.count.many': 'baixas',
    'bajas.empty': 'Sem correspondências.',
    'bajas.peso': 'peso',
    'bajas.longitud': 'comprimento',
    'bajas.causa': 'Causa provável',
    'bajas.necro.done': 'Necropsia: ',
    'bajas.necro.pending': 'Necropsia em andamento',
    'bajas.necro.none': 'Sem necropsia',
    'bajas.open': 'Ver ficha memorial',
    'bajas.hint': 'Toque para ver sua história',
    'bajas.memorial.badge': 'Em memória',
    'bajas.memorial.edad': 'Idade',
    'bajas.memorial.firstRecord': 'Primeiro registro',
    'bajas.memorial.lastRecord': 'Último registro',
    'bajas.memorial.weightTrend': 'Tendência de peso',
    'modal.memorial.badge': 'Em memória',
    'tweaks.title': 'Ajustes',
    'tweaks.theme': 'Tema',
    'tweaks.theme.dark': 'Escuro',
    'tweaks.theme.light': 'Claro',
    'tweaks.locale': 'Idioma',
    'tweaks.groupBy': 'Agrupar',
    'tweaks.groupBy.station': 'Estação',
    'tweaks.groupBy.species': 'Espécie',
    'tweaks.larvario': 'Mostrar larvário',
    'species.A. andersoni.common': 'Salamandra do Lago Zacapu',
    'species.A. mexicanum.common': 'Axolote mexicano',
    'species.A. dumerilii.common': 'Salamandra do Lago Pátzcuaro',
  },
};

export function s(locale: Locale, key: string, fallback?: string): string {
  return STRINGS[locale]?.[key] ?? STRINGS.es[key] ?? fallback ?? key;
}

export function commonName(locale: Locale, species: SpeciesCode | string | null | undefined): string {
  if (!species) return '';
  return STRINGS[locale]?.[`species.${species}.common`] ?? '';
}

export function genderTitle(locale: Locale, g: string | null | undefined): string {
  if (!g) return s(locale, 'genero.u');
  const x = String(g).toLowerCase();
  if (x.startsWith('hembra')) return s(locale, 'genero.h');
  if (x.startsWith('macho')) return s(locale, 'genero.m');
  return s(locale, 'genero.u');
}

// Shared date formatter — reuses the waterQuality month dictionary.
import { monthLabel } from '../waterQuality/strings';

export function formatDateLong(locale: Locale, iso: string | null | undefined): string {
  if (!iso) return '—';
  const [y, m, d] = iso.split('-').map(Number);
  if (!y || !m || !d) return iso;
  const month = monthLabel(locale, m - 1);
  if (locale === 'en') return `${month} ${d}, ${y}`;
  return `${d} de ${month} ${y}`;
}
